---
# tasks file for roles/configure
- name: Subscribe to RH
  redhat_subscription:
    state: present
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    auto_attach: true

- name: Install a list of packages
  yum:
    name: "{{ packages }}"
    state: present

- name: grpcurl
  ansible.builtin.unarchive:
    src: https://github.com/fullstorydev/grpcurl/archive/v1.5.1.tar.gz
    dest: /home/ec2-user/
    remote_src: yes

- name: Build grpcurl
  shell: go build
  args:
    chdir: /home/ec2-user/grpcurl-1.5.1/cmd/grpcurl/

- name: Move grpcurl
  shell: mv /home/ec2-user/grpcurl-1.5.1/cmd/grpcurl/grpcurl /usr/bin/

- name: Ensure all packages are up to date
  yum:
    name: '*'
    state: latest

- name: Copy AAP2 - Ansible Automation Platform
  ansible.builtin.unarchive:
    src: ansible-automation-platform-setup-2.1.0-1.tar.gz
    dest: /home/ec2-user/
  ignore_errors: True

- name: Ansible Tower Installer
  ansible.builtin.unarchive:
    src: ansible-tower-setup-latest (1).tar.gz
    dest: /home/ec2-user/
  ignore_errors: True

- name: Pull latest OpenShift CLI
  ansible.builtin.unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Pull latest OpenShift Installer
  ansible.builtin.unarchive:
    src: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Pull latest OpenShift Installer Mirroring Tool
  ansible.builtin.unarchive:
    src: https://developers.redhat.com/content-gateway/file/pub/openshift-v4/clients/mirror-registry/1.0/mirror-registry.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Install AWSCLI
  pip:
    name: awscli
    extra_args: --upgrade
    executable: pip3

- name: Configure AWS.
  shell: aws configure set {{ item.key }} {{ item.value }}
  no_log: True
  with_dict:
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_region }}"
    format: "{{ aws_format }}"
  become_user: "{{ ansible_user }}"
  changed_when: false

- name: Create a login user
  user:
    name: "{{ user }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - wheel
    state: present

- name: Edit EC2-USER password
  user:
    name: "{{ ansible_user }}"
    password: "{{ password | password_hash('sha512') }}"

- name: Pull in the Git Repo for OCP Shortcuts
  git:
    repo: https://github.com/afouladi7/openshift_shortcuts.git
    dest: /home/ec2-user/openshift_shortcuts

- name: Start and enable Podman
  systemd:
    name: podman
    state: started
    enabled: yes

- name: Start and enable RHEL Cockpit
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes